// ── VGC Browser — auto-update (electron-updater) ─────────────────────────────
// Checks vgcbrowser.com/dl for a newer build (reads latest.yml), auto-downloads
// it in the background, and lets the user restart to install — exactly like the
// "check for update → download → update" flow in other desktop tools.
//
// Only runs in the packaged app. In dev it is a no-op (electron-updater needs the
// installed .exe + app-update.yml generated by electron-builder).

import { app, BrowserWindow, shell } from 'electron'
import electronUpdater from 'electron-updater'
import type { UpdateStatus } from '../shared/types'

const { autoUpdater } = electronUpdater

const MAC_DOWNLOAD_PAGE = 'https://vgcbrowser.com/'

let lastStatus: UpdateStatus = { phase: 'idle', currentVersion: app.getVersion() }

// Set true when the user explicitly clicks "restart & install" so the on-quit installer
// RELAUNCHES the app afterward. A plain window-close just installs quietly without
// reopening (the user closed the app — don't force it back open).
let relaunchAfterInstall = false

function broadcast(s: UpdateStatus): void {
  lastStatus = s
  for (const w of BrowserWindow.getAllWindows()) {
    if (!w.isDestroyed()) w.webContents.send('update:status', s)
  }
}

export function getUpdateStatus(): UpdateStatus {
  return lastStatus
}

/** Wire electron-updater events and schedule periodic checks. Call once on ready. */
export function initUpdater(): void {
  if (!app.isPackaged) return // dev build: no updater

  // Release builds are code-signed on both platforms; electron-updater verifies the
  // platform signature before installation.
  autoUpdater.autoDownload = true
  autoUpdater.autoInstallOnAppQuit = true
  autoUpdater.allowDowngrade = false
  autoUpdater.allowPrerelease = false
  autoUpdater.logger = null

  autoUpdater.on('checking-for-update', () =>
    broadcast({ phase: 'checking', currentVersion: app.getVersion() })
  )
  autoUpdater.on('update-available', (info) =>
    broadcast({
      phase: 'available',
      currentVersion: app.getVersion(),
      newVersion: info.version,
      ...(process.platform === 'darwin' ? { manualDownloadUrl: MAC_DOWNLOAD_PAGE } : {})
    })
  )
  autoUpdater.on('update-not-available', () =>
    broadcast({ phase: 'up-to-date', currentVersion: app.getVersion() })
  )
  autoUpdater.on('download-progress', (p) =>
    broadcast({
      phase: 'downloading',
      currentVersion: app.getVersion(),
      percent: Math.round(p.percent)
    })
  )
  autoUpdater.on('update-downloaded', (info) =>
    broadcast({ phase: 'downloaded', currentVersion: app.getVersion(), newVersion: info.version })
  )
  autoUpdater.on('error', (err) =>
    broadcast({
      phase: 'error',
      currentVersion: app.getVersion(),
      message: err == null ? 'Lỗi không xác định' : err.message || String(err)
    })
  )

  // Check shortly after launch, then every 6 hours.
  setTimeout(() => void autoUpdater.checkForUpdates()?.catch(() => {}), 8000)
  setInterval(() => void autoUpdater.checkForUpdates()?.catch(() => {}), 6 * 60 * 60 * 1000)
}

/** Manual "Check for updates" trigger from the UI. */
export async function checkForUpdates(): Promise<UpdateStatus> {
  if (!app.isPackaged) {
    const s: UpdateStatus = {
      phase: 'dev',
      currentVersion: app.getVersion(),
      message: 'Tự cập nhật chỉ chạy ở bản đã cài đặt (.exe), không chạy ở chế độ dev.'
    }
    broadcast(s)
    return s
  }
  try {
    await autoUpdater.checkForUpdates()
  } catch (e) {
    broadcast({
      phase: 'error',
      currentVersion: app.getVersion(),
      message: e instanceof Error ? e.message : String(e)
    })
  }
  return lastStatus
}

/**
 * Quit and install the downloaded update. Triggers the app's graceful-quit path
 * (stop profiles + cloud-sync) before the NSIS installer takes over, then relaunches.
 */
export function installUpdate(): void {
  if (!app.isPackaged || lastStatus.phase !== 'downloaded') return
  // DON'T call quitAndInstall() here. It races the app's before-quit handler, which
  // preventDefault()s the quit and runs gracefulQuit → installOnQuit → quitAndInstall
  // AGAIN; electron-updater rejects that second call ("quitAndInstall called twice") so
  // the app ends up closing WITHOUT relaunching — the button looked broken. Instead just
  // flag a relaunch and ask the app to quit; gracefulQuit's installOnQuit() does the one,
  // authoritative install (after stopping profiles + cloud-syncing sessions).
  relaunchAfterInstall = true
  app.quit()
}

/** True when a newer version has finished downloading and is ready to install. */
export function hasDownloadedUpdate(): boolean {
  return app.isPackaged && lastStatus.phase === 'downloaded'
}

/**
 * Install the downloaded update WITHOUT relaunching (used on the graceful-quit path so
 * fully quitting the app applies a pending update). electron-updater's auto-install-on-
 * quit hooks the 'quit' event, but our gracefulQuit uses app.exit(0) which never emits
 * it — so the download sat "pending" forever on an always-on VPS. Spawn the installer
 * explicitly instead. `isForceRunAfter=false` → install on exit, don't relaunch.
 */
export function installOnQuit(): void {
  try {
    // isSilent=true (per-user oneClick NSIS → no elevation, runs quietly). Relaunch only
    // when the user clicked "restart & install"; a plain quit installs without reopening.
    autoUpdater.quitAndInstall(true, relaunchAfterInstall)
  } catch {
    /* fall through to the caller's app.exit */
  }
}

/** Open the download page in the default browser (macOS manual-update path). */
export function openDownloadPage(): void {
  void shell.openExternal(lastStatus.manualDownloadUrl || MAC_DOWNLOAD_PAGE)
}
