// ── VGC Browser — auto-update (electron-updater) ─────────────────────────────
// Checks vgcbrowser.com/dl for a newer build (reads latest.yml), auto-downloads
// it in the background, and lets the user restart to install — exactly like the
// "check for update → download → update" flow in other desktop tools.
//
// Only runs in the packaged app. In dev it is a no-op (electron-updater needs the
// installed .exe + app-update.yml generated by electron-builder).

import { app, BrowserWindow, shell } from 'electron'
import electronUpdater from 'electron-updater'
import type { UpdateStatus } from '../shared/types'

const { autoUpdater } = electronUpdater

// macOS auto-install needs an Apple Developer ID signature (Squirrel.Mac rejects an
// unsigned update with "Code signature did not pass validation"). The app isn't
// signed, so on Mac we only CHECK for a newer version and send the user to the
// download page to install the .dmg manually. Windows auto-updates normally.
const isMac = process.platform === 'darwin'
const MAC_DOWNLOAD_PAGE = 'https://vgcbrowser.com/'

let lastStatus: UpdateStatus = { phase: 'idle', currentVersion: app.getVersion() }

function broadcast(s: UpdateStatus): void {
  lastStatus = s
  for (const w of BrowserWindow.getAllWindows()) {
    if (!w.isDestroyed()) w.webContents.send('update:status', s)
  }
}

export function getUpdateStatus(): UpdateStatus {
  return lastStatus
}

/** Wire electron-updater events and schedule periodic checks. Call once on ready. */
export function initUpdater(): void {
  if (!app.isPackaged) return // dev build: no updater

  // On Mac we can't install an unsigned update, so don't download it (the download
  // would only end in a signature-validation error). Just check + prompt manual.
  autoUpdater.autoDownload = !isMac
  autoUpdater.autoInstallOnAppQuit = !isMac
  autoUpdater.logger = null

  autoUpdater.on('checking-for-update', () =>
    broadcast({ phase: 'checking', currentVersion: app.getVersion() })
  )
  autoUpdater.on('update-available', (info) =>
    broadcast({
      phase: 'available',
      currentVersion: app.getVersion(),
      newVersion: info.version,
      // Mac stays at 'available' (no auto-download) with a manual-download link.
      ...(isMac ? { manualDownloadUrl: MAC_DOWNLOAD_PAGE } : {})
    })
  )
  autoUpdater.on('update-not-available', () =>
    broadcast({ phase: 'up-to-date', currentVersion: app.getVersion() })
  )
  autoUpdater.on('download-progress', (p) =>
    broadcast({
      phase: 'downloading',
      currentVersion: app.getVersion(),
      percent: Math.round(p.percent)
    })
  )
  autoUpdater.on('update-downloaded', (info) =>
    broadcast({ phase: 'downloaded', currentVersion: app.getVersion(), newVersion: info.version })
  )
  autoUpdater.on('error', (err) =>
    broadcast({
      phase: 'error',
      currentVersion: app.getVersion(),
      message: err == null ? 'Lỗi không xác định' : err.message || String(err)
    })
  )

  // Check shortly after launch, then every 6 hours.
  setTimeout(() => void autoUpdater.checkForUpdates()?.catch(() => {}), 8000)
  setInterval(() => void autoUpdater.checkForUpdates()?.catch(() => {}), 6 * 60 * 60 * 1000)
}

/** Manual "Check for updates" trigger from the UI. */
export async function checkForUpdates(): Promise<UpdateStatus> {
  if (!app.isPackaged) {
    const s: UpdateStatus = {
      phase: 'dev',
      currentVersion: app.getVersion(),
      message: 'Tự cập nhật chỉ chạy ở bản đã cài đặt (.exe), không chạy ở chế độ dev.'
    }
    broadcast(s)
    return s
  }
  try {
    await autoUpdater.checkForUpdates()
  } catch (e) {
    broadcast({
      phase: 'error',
      currentVersion: app.getVersion(),
      message: e instanceof Error ? e.message : String(e)
    })
  }
  return lastStatus
}

/**
 * Quit and install the downloaded update. Triggers the app's graceful-quit path
 * (stop profiles + cloud-sync) before the NSIS installer takes over, then relaunches.
 */
export function installUpdate(): void {
  if (!app.isPackaged || lastStatus.phase !== 'downloaded') return
  // The installer is spawned first and waits for this process to exit, so the
  // existing before-quit handler (stop + cloud sync) still runs cleanly.
  autoUpdater.quitAndInstall()
}

/** Open the download page in the default browser (macOS manual-update path). */
export function openDownloadPage(): void {
  void shell.openExternal(lastStatus.manualDownloadUrl || MAC_DOWNLOAD_PAGE)
}
